config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions"}
    root "homepage#index"
    get "/messages/new" => "messages#new"
    post "/messages" => "messages#create"
    get "/messages" => "messages#chat"

    mount ActionCable.server, at: '/cable'

    get '/users/:id', to: 'users#show', as: 'user_show'
    get '/users/:id/edit', to: 'users#profile', as: 'user_profile_edit'
    patch '/users/:id', to: 'users#update', as: 'user_update'
    get '/searches/:zip', to: 'searches#show'
    get '/users_skill', to: 'homepage#users_skill'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: User, foreign_key: :sender_id
  belongs_to :reciever, class_name: User, foreign_key: :reciever_id

  validates :content, :sender_id, :reciever_id, presence: true
end

app/models/my_mailer.rb
class MyMailer < Devise::MyMailer
  helper :application
  default template_path: 'devise/mailer'
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :sent_messages, class_name: Message, foreign_key: :sender_id
  has_many :recieved_messages, class_name: Message, foreign_key: :reciever_id
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>"},:default_url => lambda { |av| ":style/missing_#{av.instance.default_image_number}.png" },  path: 'public/system/:class/:hash.:extension', url: '/system/:class/:hash.:extension', hash_secret: 'abfa04a42c94f58d17a509bccb2276d2f2e1718e23de5f0ff4bc93b4c922c2dbd23f81b31a7932fbf4424c95f14e055639d2376f8b3cb40ebf91ea4682197645'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
# default_url: ":style/missing.png",
  validates_attachment_size :image, less_than: 2.megabytes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_users_from_zip(zip)
    users = []
    self.all.each do |user|
      if user.location == zip
        users << user
      end
    end
    return users
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def recent_messages
    Message.where(sender_id: self.id).or(Message.where(reciever_id: self.id)).order(created_at: :desc)
  end

  def recent_contacts
    contacts = []
    recent_messages.each do |message|
      if message.reciever == self
        contacts.push(message.sender)
      else
        contacts.push(message.reciever)
      end
    end
    contacts.uniq[0..4]
  end

  

  def default_image_number
    id.to_s.last
  end

end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  helper_method :resource_name, :resource, :devise_mapping  
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    @users = User.all
    @skills = Skill.all
    if request.xhr?
      return render json: @users
    end
    render "/homepage/index"
  end

  def users_skill
    @skill = Skill.find_by(name: params[:skill])
    @users = @skill.users
    if request.xhr?
      return render json: @users
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def new
    render "messages/new", layout: false
  end

  def create
    message = current_user.sent_messages.build(message_params)
    message.reciever_id = params[:reciever_id]
    if message.save
      ActionCable.server.broadcast 'chat_channel',
                                   content:  message.content,
                                   username: message.sender.first_name,
                                   created_at: message.created_at,
                                   sender: message.sender,
                                   reciever: message.reciever 
      # head :ok
    else
      @errors = message.errors.full_messages
    end

  end

  def chat
    @messages = Message.where(sender_id: current_user.id, reciever_id: params[:reciever_id]).or(Message.where(sender_id: params[:reciever_id], reciever_id: current_user.id)).order(created_at: :asc)
    # messages_two =
    # messages = messages_one + messages_two
    # @messages = messages.order(created_at: :asc)
    if request.xhr?
      render partial: "new"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :reciever_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super
    @user = resource
    MyMailer.welcome_email(@user).deliver_now
  end

  def after_sign_up_path_for(resource)
    "/users/#{resource.id}" # Or :prefix_to_your_route
  end


  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :dob, :location, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :dob, :location, :email, :password, :password_confirmation)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
    @users = User.find_users_from_zip(params[:zip])

    if params[:skill] != "All"
      @user_select = @users.select do |user|
        skill = Skill.find_by(name: params[:skill])
        user.skills.include? skill
      end
    else
      @user_select = @users
    end

    if request.xhr?
      render layout: false
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
    puts '-----------------------------------------------------------------------'
    if request.xhr?
      puts "----------------------------------------------------------------------"
      render 'devise/sessions/new', layout: false
    end
  end

  # POST /resource/sign_in
  def create
    # super
    if request.xhr?
      puts '-----------------------------aksjdakjsdh---------------------------------------------'
      self.resource = warden.authenticate!(auth_options)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    else
      self.resource = warden.authenticate!(auth_options)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    puts params.inspect
    @user = User.find(params[:id])
    @recent_contacts = @user.recent_contacts
  end

  def profile
    @user = User.find(params[:id])
    if !(user_signed_in? && @user == current_user)
      redirect_to :root
    end
  end

  def update
    @user = User.find(params[:id])
    if user_signed_in? && @user == current_user
      @user.update(account_update_params)
      if @user.save
        redirect_to user_show_path
      end
    else
      @errors = @user.errors.full_messages
      redirect_to user_show_path
    end
  end

  private

  def account_update_params
    params.require(:user).permit(:image, :first_name, :last_name, :dob, :location, :summary, :interests, :email, skill_ids: [])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/_list.html.erb
<ul>
  <% User.all.each do |user| %>
    <li><%= user.first_name %> <%= user.last_name  %></li>
  <% end %>
</ul>

app/views/homepage/_sidebar.html.erb
<h3>Welcome to levelUp!</h3>
<span>A website for lifelong learners looking to share their knowledge.</span>
<ol>
  <li id="step-one">Choose a skill to search for from the dropdown menu.</li>
  <li id="step-two">Specify a zipcode to find lifelong learners near you!</li>
  <li id="step-three"><b>ENTER</b> a world of knowledge and connect with those who share your interests and skills</li>
</ol>

app/views/homepage/index.html.erb
<div class="container search-form center-block">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
		    <div class="input-group">
                <div class="input-group-btn search-panel">

               		<select id="select-skill" class="btn btn-default move-front" data-toggle="dropdown">
					       	<option value="All">All</option>
					  	    <% @skills.each do |skill| %>
					    	    <option value="<%=skill.name%>"><%=skill.name%></option>
					  	    <% end %>
					       </select>
				        </div>
                <!-- <input type="hidden" name="search_param" value="all" id="search_param"> -->
                <input id="search-input" type="text" class="form-control" name="search" placeholder="Search by zip code">
                <span class="input-group-btn">
                    <button id="submit-skill" class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                </span>
            </div>
        </div>
	</div>
</div>

<div id="sidebar-peek"><i class="fa fa-info-circle fa-2x" aria-hidden="true"></i></div>
<div style="display:none" id="sidebar-full"><%= render partial: "homepage/sidebar"  %></div>
<img style="display:none" id="search-example" width="609" height="594" class="mush-logo" src=<%=image_url("search_example.png")%>>

<div id="map"></div>

<div class="scene hide">
  <img class="car" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/car.svg" alt="" />
  <img class="poof" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/poof.svg" alt="" />
  <img class="sign" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/sign.svg" alt="" />
  <em>LOADING...</em>
</div>


<div class="popup_content" id="list_popup">
</div>

app/views/layouts/_footer.html.erb
<div>
  <footer class="footer">
    <small style="color: white">
      Copyright © Level Up by
      <a href="https://github.com/nhantnon/final-learning-app">levelUpLearning</a>
    </small>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="F6RqmfrvMRKYCnUbQIhj16PfpYGrI8f2CTqrye4nT5U" />
    <title>FinalProjectLearningApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/7837c0b485.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDzWibWWs0iuPjnnwnaOpkQvVH3LhTeiIE&libraries=places">
    </script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
  crossorigin="anonymous"></script>
    <meta name="turbolinks-cache-control" content="no-cache">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <%= action_cable_meta_tag %>
</head>
<body>

  <div class="navbar-wrapper">
    <div class="container-fluid">
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div>
            <a class="navbar-brand" href="/">Level Up</a>
            <img width="80" height="40" class="mush-logo" src=<%=image_url("people.png")%>>
          </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">
            <% if user_signed_in?  %>
              <li><a href="/users/<%=current_user.id%>"><%= "#{current_user.first_name} #{current_user.last_name}" %></a></li>
              <li><a data-method="delete" href="/users/sign_out">Logout</a></li>
            <% else %>
              <li><a class='login_popup_open' id="login-link" href="/users/sign_in">Login</a></li>
              <li><a class='register_popup_open' id="register-link" href="/users/sign_up">Sign Up</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    </div>
  </div>

<div class="yield-box"></div>

  <%= yield %>

<div class="popup_content" id="login_popup">
  <%= render template: "devise/sessions/new" %>
</div>

<div class="popup_content" id="register_popup">
  <%= render template: "devise/registrations/new" %>
</div>
  <%= render 'layouts/footer' %>
</body>

</html>

app/views/messages/_messages.html.erb
<ul id="message-board" data-chatroom="<%=current_user.id%>_<%=params[:reciever_id]%>">
  <%@messages.each do |message|%>
    <%if message.sender == current_user%>
      <li class="user_one_message"><div id="user_one_message"><b><%= message.sender.first_name%></b>: <%=message.content%></div></li>
    <%else%>
      <li class="user_two_message"><div id="user_two_message"><b><%= message.sender.first_name%></b>: <%=message.content%></div></li>
    <%end%>
  <%end%>
</ul>

app/views/messages/_new.html.erb
<div id="close_chat">Close Chat</div>
<div id="chat-container" >
  <%=render partial: "messages"%>
</div>

<%= form_for :message, html: {id: "message_form"}, :url => "/messages?reciever_id=#{params[:reciever_id]}" do |f| %>
  <%= f.text_area :content %><br/>

  <input type="submit" value="Send Message">
<% end %>

app/views/searches/show.html.erb
<div id="learner-list">
  <h1>Connect with these lifelong learners!</h1>
  <table class='table'>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  <% @user_select.each do |user| %>
    <tr>
      <td><%= user.first_name %> <%= user.last_name %></td>
      <td><%= link_to 'Connect!', user_show_path(user), class: "user_link" %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/users/profile.html.erb
<div id="edit-note">
    You are now viewing <strong>edit</strong> mode
</div>
<div class="container userInfo">
<div class="row">
<%= bootstrap_form_for(@user, url: user_update_path, html: {:multipart => true}) do |f| %>
    <div class="col-sm-12">
        <div class="panel panel-default">
               <div class="panel-heading resume-heading">
                  <div class="row">
                     <div class="col-lg-12">
                        <div class="col-xs-12 col-sm-4">
                           <figure class="text-center">
                              <%= image_tag(@user.image.url(:medium), :class => "img-thumbnail img-responsive center-block") %>
                              <%= f.file_field :image, label: "Update your profile image", help: "Image must be less than 2 megabytes" %>
                           </figure>
                           <div class="row">

                           </div>
                        </div>
                        <div class="col-xs-12 col-sm-8">
                           <ul class="list-group">
                              <li class="list-group-item form-inline">
                                <h2>
                                <%= f.text_field :first_name, autofocus: true, hide_label: true, placeholder: "First name" %>
                                <%= f.text_field :last_name, autofocus: true, hide_label: true, placeholder: "Last name"  %>
                                </h2>
                              </li>
                              <li class="list-group-item form-inline"><i class="fa fa-birthday-cake"></i>
                                <%= f.date_field :dob, autofocus: true, hide_label: true %>
                              </li>
                              <li class="list-group-item form-inline"><i class="fa fa-map-marker"></i>
                                <%= f.text_field :location, autofocus: true, hide_label: true, placeholder: "Zip Code" %>
                              </li>
                              <li class="list-group-item form-inline"><i class="fa fa-envelope"></i> 
                                <%= f.email_field :email, autofocus: true, hide_label: true, placeholder: "Email address" %>
                              </li>
                           </ul>
                           <%= f.submit "Update", :class => "btn btn-success form-inline" %>
                           <%= link_to 'Cancel', user_show_path, class: "btn btn-default"%>
                        </div>
                     </div>
                  </div>
               </div>

               <div class="bs-callout bs-callout-green">
                  <h4>Summary</h4>
                  <ul class="list-group">
                        <p>
                          <%= f.text_area :summary, autofocus: true, hide_label: true, placeholder: "Add a summary about yourself" %>
                        </p>
                  </ul>
               </div>

               <div class="bs-callout bs-callout-green">
                  <h4>Interests</h4>
                  <ul class="list-group">
                        <p>
                          <%= f.text_area :interests, autofocus: true, hide_label: true, placeholder: "Add your interests" %>
                        </p>
                  </ul>
               </div>

               <div class="bs-callout bs-callout-green">
                  <h4>Skills</h4>
                  <ul class="list-group">
                    <div>
                      <% Skill.all.each do |skill| %>
                      <label>
                          <%= check_box_tag "user[skill_ids][]", skill.id, f.object.skills.include?(skill) %>
                          <%= skill.name %>
                      <% end %>
                    </div>
                  </ul>
               </div>

            </div>
         </div>
    </div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<script type="text/javascript"></script>

<div class="container userInfo">
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
               <div class="panel-heading resume-heading">
                  <div class="row">
                     <div class="col-lg-12">
                        <div class="col-xs-12 col-sm-4">
                           <figure>
                              <%= image_tag(@user.image.url(:medium), :class => "img-thumbnail img-responsive center-block") %>
                           </figure>
                           <div class="row">
                                <%if user_signed_in? && current_user != @user%>
                                <a href="/messages/<%=params[:id]%>" id="chat-button" class="btn btn-green btn-block btn-compose-email">Chat With <%=@user.first_name  %></a>
                                <%end%>

                           </div>
                        </div>
                        <div class="col-xs-12 col-sm-8">
                           <ul class="list-group">
                              <li class="list-group-item"><h2><%=@user.first_name + " " + @user.last_name%></h2></li>
                              <li class="list-group-item"><i class="fa fa-birthday-cake"></i>  <%=@user.dob.strftime("%B %d")%></li>
                              <li class="list-group-item"><i class="fa fa-map-marker"></i>  <%=@user.location%></li>
                              <li class="list-group-item"><i class="fa fa-envelope"></i> <%=@user.email%></li>
                           </ul>
                           <% if @user == current_user %>
                            <div id="edit-contact-container">
                             <%= link_to 'Edit Profile', user_profile_edit_path, class: "btn btn-default edit-user-button"%>
                             <ul id="contacted-users">
                                <li id="contacts-heading">Recent Contacts:</li>
                              <%@recent_contacts.each do |user|%>
                                <li><a href="/users/<%=user.id%>"><%=user.full_name%></a></li>
                              <%end%>
                             </ul>
                            </div>
                           <% end %>
                        </div>
                     </div>
                  </div>
               </div>

               <div class="bs-callout bs-callout-green">
                  <h4>Summary</h4>
                  <ul class="list-group">
                      <%if @user.summary %>
                          <p>
                            <%=@user.summary%>
                          </p>
                      <%else%>
                        <p class="list-group-item"><%=@user.first_name%> has not listed a summary</p>
                      <%end%>
                  </ul>
               </div>

               <div class="bs-callout bs-callout-green">
                  <h4>Interests</h4>
                  <ul class="list-group">
                      <%if @user.interests %>
                          <p>
                            <%=@user.interests%>
                          </p>
                      <%else%>
                        <p class="list-group-item"><%=@user.first_name%> has not listed any interests</p>
                      <%end%>
                  </ul>
               </div>

               <div class="bs-callout bs-callout-green">
                  <h4>Skills</h4>
                  <ul class="list-group">
                      <%if @user.skills.length > 0 %>
                        <%@user.skills.each do |skill|%>
                          <li class="list-group-item">
                            <%=skill.name%>
                          </li>
                        <%end%>
                      <%else%>
                        <li class="list-group-item"><%=@user.first_name%> has not listed any skills</li>
                      <%end%>
                  </ul>
               </div>

            </div>
         </div>
    </div>
</div>
</div>